### ISSUE TITLE
Importing Compendiums names display weirdly

### ISSUE THREAD

**Issue by CyricPL** [hitcherland/FoundryVTT-Heart#51]
When importing compendium items into the local world, the names display in an odd format. While it is certainly possible to work from the compendiums directly, it would be nice to import so that they can be sorted into sub-folders.

<img width="327" alt="image" src="https://github.com/hitcherland/FoundryVTT-Heart/assets/20262774/12b88899-c2c7-4062-9a73-d116ee762d7b">

**Comment by Wigginns** [comment]
This also happens with the description of Beats and a few other things. I know this issue has something to do with the localization setup but I haven't yet cracked how to fix it. 

In the meantime, as a workaround, you should be able to "open" the item and then close it and the name *should* fix.

**Comment by CyricPL** [comment]
Opening them does work to update the name. Another odd behavior; if I go to edit any fallout that I imported, instead of getting the actual text in the edit box it then turns to "fallout.major.blood.arterial_wound.description," as an example. The only way to fix it was then to manually put the text back in. I was editing as I wanted to add a link to the "Bleeding" item using the UUID, since the text says "As BLEEDING," and in addition to discovering this happens in the descriptions I also found the UUID links don't work within Fallout item descriptions.

**Comment by hitcherland** [comment]
Oh that's frustrating. As a background explanation, I didn't want to have to add multiple packs for each language, but perhaps this is biting us a bit. I feel like I have fixed the "text in box is the translation id" thing somewhere else, but it's a workaround so that might be broken now.

The UUID links not working is interesting, as I specifically overrode the "getUUID" function to allow my hack to work. If that's broken in recent versions this will require a hefty refactor of the translation workarounds.

**Comment by hitcherland** [comment]
I have a slightly hacky workaround in for v0.8.3 which fixes this. I'm going to close, but let me know if dragging them across doesn't work for you.
